config/routes.rb
Arizonacollab::Application.routes.draw do
  resources :spaces

  

end

app/models/space.rb
class Space < ActiveRecord::Base
  has_paper_trail
  acts_as_gmappable

  before_update :update_lat_lng

  attr_accessor :dot_color

  def self.categories
    # Downcased and capitalized for great justice
    Space.all.select(:category).map{|s| s.category.downcase.capitalize }.uniq
  end

  def self.dot_colors
    ["red","blue","green","yellow","purple","orange"]
  end

  def website_with_protocol
    /^http/.match(self.website) ? self.website : "http://#{self.website}"
  end

  def full_address
    "#{self.address}, #{self.city} #{self.state}" 
  end

  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    self.full_address
  end

  def update_lat_lng
    coords = self.geocode.first
    Rails.logger.info coords.inspect
    self.latitude = coords[:lat]
    self.longitude = coords[:lng]
  end

  def geocode
    Gmaps4rails.geocode(self.full_address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def info_for_paper_trail
    { :whodunnit => request.remote_ip }
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all

    # Index, downcase, and capitalize the categories
    dot_index = 0
    @spaces.group_by{|s| s.category.downcase}.each do |group|
      dot_color = Space.dot_colors[dot_index]
      group.last.each do |space|
        space.category = group.first.capitalize
        space.dot_color = dot_color
      end
      dot_index += 1
    end

    # Don't bother with generating markers for JSON
    respond_to do |format|
      format.html {

        @json = @spaces.to_gmaps4rails do |space, marker|
          marker.infowindow render_to_string(:partial => "/spaces/marker", :locals => { :space => space})
          marker.picture({
                          :picture => "http://maps.google.com/intl/en_us/mapfiles/ms/micons/#{space.dot_color}-dot.png",
                          :width   => 32,
                          :height  => 32
                         })
          marker.title   space.name
          marker.json({ :id => space.id })
        end
      }
      format.json #render json
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render action: 'show', status: :created, location: @space }
      else
        format.html { render action: 'new' }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :category, :address, :city, :state, :hours, :phone, :email, :website, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arizonacollab</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %> (suggested: <%= Space.categories.join(", ") %>)
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/_marker.html.erb
<div class="marker-container">
  <h3><%= space.name %></h3>
  <em><%= space.category %></em>

  <p>
    <%= space.full_address %><br/>

    <strong>Hours:</strong> <%= space.hours %><br/>

    <strong>Phone:</strong> <%= space.phone %><br/>

    <strong>Email:</strong> <%= space.email %><br/>

    <strong>Website:</strong> <%= link_to space.website, space.website_with_protocol %><br/>
  </p>

  <p>
    <%= space.description %>
  </p>
</div>

app/views/spaces/_space.html.erb
<p>
  <strong>Name:</strong>
  <%= space.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= space.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= space.full_address %>
</p>

<p>
  <strong>Latitude/Longitude:</strong>
  <%= space.latitude %>, <%= space.longitude %>
</p>

<p>
  <strong>Hours:</strong>
  <%= space.hours %>
</p>

<p>
  <strong>Phone:</strong>
  <%= space.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= space.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= space.website %>
</p>

<p>
  <strong>Description:</strong>
  <%= space.description %>
</p>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<%= stylesheet_link_tag 'gmaps4rails' %>

<h1>Collaborative Spaces in Arizona</h1>
<p>
  <%= link_to 'Add Space', new_space_path %> | 
  <%= link_to 'JSON Feed', spaces_path("json") %>
</p>

<%= gmaps4rails(@json) %>

<%= yield :scripts %>

<br/>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Hours</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Website</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.group_by{|s| s.category}.each do |category, spaces| %>
      <tr><th colspan="7" style="text-align: left;">
        <span style="color: <%= spaces.first.dot_color %>">&bull;</span>
      <%= category.titleize.pluralize %></th></tr>
      <% spaces.each do |space| %>
        <tr>
          <td><%= space.name %></td>
          <td><%= space.full_address %></td>
          <td><%= space.hours %></td>
          <td><%= space.phone %></td>
          <td><%= space.email %></td>
          <td><%= space.website %></td>
          <td><%= space.description %></td>
          <td><%= link_to 'Show', space %></td>
          <td><%= link_to 'Edit', edit_space_path(space) %></td>
          <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "space", locals: {space: @space} %>

<%= link_to 'Edit', edit_space_path(@space) %>

<h3>Revision history</h3>
<dl>
<% @space.versions.reverse!.each do |v| %>
  <dt><b><%= v.event.capitalize %> <%= v.created_at %> <%= v.whodunnit if v.whodunnit %></b></dt>
  <dd>
    <% if v.reify %>
      <%= render partial: "space", locals: {space: v.reify} %>
    <% end %>
  </dd>
<% end %>
</dl>